version: '3.8'

services:
  laravel.test:
    build:
      context: ./trainees/vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.2/app
    container_name: maquina2-laravel
    hostname: maquina2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'      # Porta 80 para acesso direto
      - '5173:5173'  # Vite para desenvolvimento
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      # Configurações vulneráveis para treinamento
      APP_DEBUG: 'true'
      APP_ENV: 'local'
      LOG_LEVEL: 'debug'
      # Configurações do banco
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_DATABASE: 'laravel'
      DB_USERNAME: 'sail'
      DB_PASSWORD: 'password'
    volumes:
      - './trainees:/var/www/html'
      # Logs expostos para Elastic
      - ./logs/system:/var/log/system
      - ./logs/php:/var/log/php
      - ./logs/laravel:/var/www/html/storage/logs
      - ./logs/app:/var/log/app
      - ./logs/access:/var/log/access
      - ./logs/error:/var/log/error
      - ./logs/debug:/var/log/debug
      # Arquivos vulneráveis
      - ./vulnerable_files:/opt/vulnerable_files
      - ./uploads:/var/www/html/storage/app/public/uploads
      - ./backups:/var/www/html/storage/backups
      - ./configs:/etc/configs
      # Docker socket para escape
      - /var/run/docker.sock:/var/run/docker.sock
      # Home directory persistente
      - ./home:/home
    networks:
      - soc-network
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailpit
      - selenium
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    privileged: true
    user: root
    command: ["/bin/bash", "-c", "php artisan serve --host=0.0.0.0 --port=80"]

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: maquina2-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './trainees/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      - ./logs/mysql:/var/log/mysql
    networks:
      - soc-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    container_name: maquina2-redis
    ports:
      - '6379:6379'
    volumes:
      - 'sail-redis:/data'
      - ./logs/redis:/var/log/redis
    networks:
      - soc-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    container_name: maquina2-meilisearch
    ports:
      - '7700:7700'
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - 'sail-meilisearch:/meili_data'
      - ./logs/meilisearch:/var/log/meilisearch
    networks:
      - soc-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7700/health"]
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: maquina2-mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - ./logs/mailpit:/var/log/mailpit
    networks:
      - soc-network

  selenium:
    image: selenium/standalone-chrome
    container_name: maquina2-selenium
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/dev/shm:/dev/shm'
      - ./logs/selenium:/var/log/selenium
    networks:
      - soc-network

networks:
  soc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
