version: '3.8'

services:
  # Active Directory Domain Controller
  ad-dc:
    image: servercontainers/samba-ad-dc:latest
    container_name: ad-dc
    hostname: DC01
    ports:
      - "389:389"   # LDAP
      - "636:636"   # LDAPS
      - "88:88"     # Kerberos
      - "135:135"   # RPC
      - "139:139"   # NetBIOS
      - "445:445"   # SMB
      - "464:464"   # Kerberos password change
      - "49152-49155:49152-49155"  # RPC dynamic ports
    environment:
      - DOMAIN=LAB.LOCAL
      - DOMAINPASS=Password123!
      - DNSFORWARDER=8.8.8.8
      - HOSTIP=0.0.0.0
      - INSECURELDAP=true
      - MULTISITE=false
      - NOCOMPLEXITY=true
      - USEWINDOWSACL=false
    volumes:
      - ad-data:/var/lib/samba
      - ad-config:/etc/samba/external
    networks:
      - ad-network

  # Windows Workstation (cliente)
  windows-client:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    container_name: windows-client
    hostname: WIN10
    ports:
      - "3389:3389"  # RDP
    environment:
      - DOMAIN=LAB.LOCAL
    depends_on:
      - ad-dc
    networks:
      - ad-network

  # Kali Linux para ataques
  kali:
    image: kalilinux/kali-rolling:latest
    container_name: kali-attacker
    hostname: KALI
    ports:
      - "22:22"      # SSH
      - "8080:8080"  # Web interface
    volumes:
      - ./tools:/tools
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y 
          nmap 
          metasploit-framework 
          impacket-tools 
          bloodhound 
          crackmapexec 
          responder 
          hashcat 
          john 
          python3-pip &&
        pip3 install 
          ldap3 
          pywinrm 
          requests &&
        service ssh start &&
        tail -f /dev/null
      "
    networks:
      - ad-network

volumes:
  ad-data:
  ad-config:

networks:
  ad-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 