version: '3.8'

services:
  # Graylog para centralização de logs
  graylog:
    image: graylog/graylog:4.3
    container_name: lab-siem-graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    ports:
      - "9000:9000"   # Web interface
      - "12201:12201/udp"  # GELF UDP
      - "1514:1514"   # Syslog TCP
      - "1514:1514/udp"  # Syslog UDP
    volumes:
      - graylog_data:/usr/share/graylog/data
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - lab-network

  # MongoDB para Graylog
  mongo:
    image: mongo:4.2
    container_name: lab-siem-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - lab-network

  # Elasticsearch para Graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: lab-siem-elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - lab-network

  # Wazuh Manager (SIEM alternativo)
  wazuh:
    image: wazuh/wazuh-manager:4.3.10
    container_name: lab-siem-wazuh
    ports:
      - "1515:1514"   # Syslog TCP
      - "1515:1514/udp"  # Syslog UDP
      - "514:514/udp"  # Syslog UDP (alternativo)
      - "514:514"      # Syslog TCP (alternativo)
    volumes:
      - wazuh_data:/var/ossec/data
      - wazuh_logs:/var/ossec/logs
    networks:
      - lab-network

  # Logstash para processamento de logs
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    container_name: lab-siem-logstash
    ports:
      - "5044:5044"   # Beats
      - "5000:5000/tcp"  # Logstash TCP
      - "5000:5000/udp"  # Logstash UDP
      - "9600:9600"   # Logstash API
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - lab-network

volumes:
  graylog_data:
  mongo_data:
  es_data:
  wazuh_data:
  wazuh_logs:

networks:
  lab-network:
    driver: bridge 